env:
  browser: true
  es6: true
extends:
  - google
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
rules:
  max-len:
    - error
    - code: 100
  require-jsdoc:
    - off
  indent:
    - error
    - 4
